import Head from 'next/head'
import Link from 'next/link'
import Nav from '../components/Nav'
import Results from '../components/Results'
import {trending,movies} from '../utils/requests'



export default function Home({results}) {

  return (
    <div>
      <Head>
          <title>Hulu By Tyson</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Nav movies={movies}/> */}
      
      <Results results={results}/>
    </div>
  )
}

export async function getServerSideProps(context) {
  //get the genre query value from the url
  const genre = context.query.genre;
  try {
    const res = await fetch(`https://api.themoviedb.org/3${trending.fetchTrending.url}`);  
    const data = await res.json()
    return {
    props: {
      results: data.results,
    }
  }
  } catch (error) {
    return {
      notFound: true,
    }
  }


}
