import Head from 'next/head'
import Header from '../components/Header'
import Nav from '../components/Nav'
import Results from '../components/Results'
import {seriesreq} from '../utils/requests'

const series = ({results}) => {
  return (
    <div>
      <Head>
          <title>Hulu By Tyson</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav seriesreq={seriesreq}/>
      <Results results={results}/>
          
    </div>
  )
}

export default series;

export async function getServerSideProps(context) {
    //get the genre query value from the url
  const genre = context.query.genre;
  try {
      //make an api call with url part one or default to second part if the query variable is undefined
        const res = await fetch(`https://api.themoviedb.org/3${seriesreq[genre]?.url || seriesreq.fetchTV.url}`);
    const data = await res.json()
    return {
    props: {
      results: data.results,
    }
  }
  } catch (error) {
    return {
      notFound: true,
    }
  }
  

}